### ISSUE TITLE
Agile Dashboard is not working.

### ISSUE THREAD

**Issue by ghanshyams92** [Enalean/docker-tuleap-aio#64]
Using tuleap latest image (Tuleap Version 10.8). Agile Dashboard is not working in this image.

**Comment by LeSuisse** [comment]
Hi,

I retrieved the latest image currently available on the Docker Hub and the Agile Dashboard seem to work just fine.

What does not work on your end?

**Comment by ghanshyams92** [comment]
I installed the Agile Dashboard. In the Readme section it is stated that "Agile Dashboard is under development and aims to provide a nice interface on top of trackers for management of Agile development processes. As of today, Scrum and Kanban are targeted."

![agile](https://user-images.githubusercontent.com/35167528/50350477-5062d180-0565-11e9-8594-e11307e7dbf0.jpg)

Post installation of the above mentioned plugin, Agile Dashboard is not working and just getting load without any result.

**Comment by ghanshyams92** [comment]
Correct , that Plugin is already there but its not working for me. So, tried to re-install but still same result and Agile Dashboard does not load.
I follow the below mentioned option to get backlog which is not working here: 
Project -> testProject -> Agile Dashboard -> Scrum testProject backlog.
![screenshot](https://user-images.githubusercontent.com/35167528/50391527-4e1e9400-076c-11e9-869b-bb5a6b7b619f.jpg)

**Comment by ghanshyams92** [comment]
Hi LeSuisse, there was some confusion , I  am using Tuleap version 10.7.99.47 .  
Error logs are appended here :
 
cat /opt/remi/php56/root/var/log/php-fpm/error.log
[25-Dec-2018 21:38:20] NOTICE: fpm is running, pid 399
[25-Dec-2018 21:38:20] NOTICE: ready to handle connections
[28-Dec-2018 06:12:11] WARNING: [pool tuleap] child 517 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught exception 'ParagonIE\EasyDB\Exception\ConstructorFailed' with message 'Could not create a PDO connection. Please check your username and password.' in /usr/share/tuleap/src/vendor/paragonie/easydb/src/Factory.php:57"
[28-Dec-2018 06:12:11] WARNING: [pool tuleap] child 517 said into stderr: "Stack trace:"
[28-Dec-2018 06:12:11] WARNING: [pool tuleap] child 517 said into stderr: "#0 /usr/share/tuleap/src/common/DB/DBFactory.php(47): ParagonIE\EasyDB\Factory::create('mysql:host=loca...', 'codendiadm', '5j2RyPcHgw6z1P3')"
[28-Dec-2018 06:12:11] WARNING: [pool tuleap] child 517 said into stderr: "#1 /usr/share/tuleap/src/common/DB/DBFactory.php(34): Tuleap\DB\DBFactory::getDB('tuleap')"
[28-Dec-2018 06:12:11] WARNING: [pool tuleap] child 517 said into stderr: "#2 /usr/share/tuleap/src/common/dao/CodendiDataAccess.class.php(41): Tuleap\DB\DBFactory::getMainTuleapDB()"
[28-Dec-2018 06:12:11] WARNING: [pool tuleap] child 517 said into stderr: "#3 /usr/share/tuleap/src/common/dao/include/DataAccessObject.class.php(51): CodendiDataAccess::instance()"
[28-Dec-2018 06:12:11] WARNING: [pool tuleap] child 517 said into stderr: "#4 /usr/share/tuleap/src/common/Config/ForgeConfig.php(53): DataAccessObject->__construct()"
[28-Dec-2018 06:12:11] WARNING: [pool tuleap] child 517 said into stderr: "#5 /usr/share/tuleap/src/www/include/pre.php(47): ForgeConfig::loadFromDatabase()"
[28-Dec-2018 06:12:11] WARNING: [pool tuleap] child 517 said into stderr: "#6 /usr/share/tuleap/src/www/help/index.php(22): require_once('/usr/share/tule...')"
[28-Dec-2018 06:12:11] WARNING: [pool tuleap] child 517 said into stderr: "#7 {main}"
[28-Dec-2018 06:12:11] WARNING: [pool tuleap] child 517 said into stderr: "  thrown in /usr/share/tulea..."
[28-Dec-2018 06:12:16] WARNING: [pool tuleap] child 516 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught exception 'ParagonIE\EasyDB\Exception\ConstructorFailed' with message 'Could not create a PDO connection. Please check your username and password.' in /usr/share/tuleap/src/vendor/paragonie/easydb/src/Factory.php:57"
[28-Dec-2018 06:12:16] WARNING: [pool tuleap] child 516 said into stderr: "Stack trace:"
[28-Dec-2018 06:12:16] WARNING: [pool tuleap] child 516 said into stderr: "#0 /usr/share/tuleap/src/common/DB/DBFactory.php(47): ParagonIE\EasyDB\Factory::create('mysql:host=loca...', 'codendiadm', '5j2RyPcHgw6z1P3')"
[28-Dec-2018 06:12:16] WARNING: [pool tuleap] child 516 said into stderr: "#1 /usr/share/tuleap/src/common/DB/DBFactory.php(34): Tuleap\DB\DBFactory::getDB('tuleap')"
[28-Dec-2018 06:12:16] WARNING: [pool tuleap] child 516 said into stderr: "#2 /usr/share/tuleap/src/common/dao/CodendiDataAccess.class.php(41): Tuleap\DB\DBFactory::getMainTuleapDB()"
[28-Dec-2018 06:12:16] WARNING: [pool tuleap] child 516 said into stderr: "#3 /usr/share/tuleap/src/common/dao/include/DataAccessObject.class.php(51): CodendiDataAccess::instance()"
[28-Dec-2018 06:12:16] WARNING: [pool tuleap] child 516 said into stderr: "#4 /usr/share/tuleap/src/common/Config/ForgeConfig.php(53): DataAccessObject->__construct()"
[28-Dec-2018 06:12:16] WARNING: [pool tuleap] child 516 said into stderr: "#5 /usr/share/tuleap/src/www/include/pre.php(47): ForgeConfig::loadFromDatabase()"
[28-Dec-2018 06:12:16] WARNING: [pool tuleap] child 516 said into stderr: "#6 /usr/share/tuleap/src/www/help/index.php(22): require_once('/usr/share/tule...')"
[28-Dec-2018 06:12:16] WARNING: [pool tuleap] child 516 said into stderr: "#7 {main}"
[28-Dec-2018 06:12:16] WARNING: [pool tuleap] child 516 said into stderr: "  thrown in /usr/share/tulea..."

**Comment by LeSuisse** [comment]
Does this only happen when using the agile dashboard? From the stacktrace, it looks like the MySQL server dies.

I would suggest to upgrade and then if the error is still there to check the MySQL logs.

**Comment by vaceletm** [comment]
Closing this issue because the image is officially deprecated. The new image can be found here: https://hub.docker.com/r/tuleap/tuleap-community-edition

The rational for the switch can be found here: https://tuleap.net/plugins/tracker/?aid=21334
